### ISSUE TITLE
При развертывании на standalone сервере quack не может подключиться к mongodb

### ISSUE THREAD

**Issue by krkub3** [greatbit/quack#200]
Метод развёртывания **How to run on a standalone server**
Шаги:
1. Install NGINX and add [conf/quack.conf](https://github.com/greatbit/quack/blob/master/assembly/quack.conf)
2. Run mongo, e.g.: docker run --name mongodb --restart always -p 27017:27017 -d mongo
3. Place [conf/quack.properties](https://github.com/greatbit/quack/blob/master/assembly/quack.properties) somewhere in the system (e.g. /etc/quack)

При запуске _java -Xbootclasspath/a:/etc/quack -jar /usr/quack/lib/jetty-runner.jar /usr/quack/quack.war_ в консоли среди прочего текста появляется ошибка:
**2022-04-07 15:38:12,556 [scription='null'}-mongod:27017] INFO  cluster                        - Exception in monitor thread while connecting to server mongod:27017
com.mongodb.MongoSocketException: mongod: Неизвестное имя или служба
	at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:211)[mongo-java-driver-3.12.9.jar:]
	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:75)[mongo-java-driver-3.12.9.jar:]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65)[mongo-java-driver-3.12.9.jar:]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:128)[mongo-java-driver-3.12.9.jar:]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117)[mongo-java-driver-3.12.9.jar:]
	at java.base/java.lang.Thread.run(Thread.java:829)[:]**

Если установить mongodb на сервер (не в докере), ошибка та же самая.

**Comment by azee** [comment]
https://github.com/greatbit/quack/blob/master/assembly/quack.properties#L2
Вот тут надо указать правильный эндпоинт монги

Альтернативно можно указать полный коннекшн стринг (URI)
https://github.com/greatbit/quack/blob/master/assembly/quack.properties#L6

mongodb+srv://somemongoserver:accessKey@dbnameorsomething.amtw99999.mongodb.net/DBNAME?retryWrites=true&w=majority

Если, например, завести себе serverless кластер в облаке https://www.mongodb.com/ и коннектиться туда используя URI. Или не серверлеес, тогда будет быстрее и будет работать статистика ланчей.
